<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository {

    public function listAll() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT m '
                        . ' FROM AppBundle:Movies m '
                        . ' WHERE m.imdbPoster != :imdbPoster '
                        . ' ORDER BY m.year DESC '
                )->setParameter('imdbPoster', '')
                ->setFirstResult(rand(0,100))
                ->setMaxResults(6);
        $movies = $query->getResult();
        return $movies;
    }

}
