<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function listAll($maxResult = 50)
    {
        $em = $this->getEntityManager();

        $qbPref = $em->createQueryBuilder();
        $qbPref->select('IDENTITY(p.idMovie)')
          ->from('AppBundle:Preference', 'p');

        $qbMovie = $em->createQueryBuilder();
        $qbMovie->select('m')
          ->from('AppBundle:Movie', 'm')
          ->where('m.imdbPoster != :imdbPoster')
          ->andWhere('m.year <= :year')
          ->andWhere('m.duration > :duration')
          //->andWhere('m.imdbRating > :imdbRating')
          //->andWhere($qbMovie->expr()->notIn('m.idMovie', $qbPref->getDQL()))
          ->orderBy('m.year', 'DESC')
          ->setParameter('imdbPoster', '')
          ->setParameter('year', 2014)
          ->setParameter('duration', 60);

          if ($maxResult > 0) {
            $qbMovie->setMaxResults(30);
          }
          //->setParameter('imdbRating', 7)


        $query = $qbMovie->getQuery();
        $movies = $query->getResult();

        return $movies;
    }
}
